"""OpenMontage image provider — scene art from OpenMontage's local engine.

Uses tools/graphics/local_diffusion.py (local Stable Diffusion via diffusers)
from github.com/calesthio/OpenMontage in a separate process. Scene prompts are
the AI-written ones from the storyboard pass. When the real OpenMontage repo
(with its tools/ package) is connected via OPENMONTAGE_REPO, scene art is
generated by OpenMontage; otherwise SongForge falls back to its placeholder
art engine, so the pipeline never blocks.
"""
import json
import subprocess
from pathlib import Path

from .base import ImageProvider, ProviderUnavailable
from ..config import SETTINGS

_RUNNER = Path(__file__).resolve().parents[3] / "tools" / "openmontage_genimage.py"


class OpenMontageImageProvider(ImageProvider):
    name = "openmontage"

    def _real_repo(self) -> Path | None:
        """OPENMONTAGE_REPO must be a real OpenMontage clone (has tools/)."""
        repo = Path(SETTINGS.openmontage_repo) if SETTINGS.openmontage_repo else None
        if repo and (repo / "tools" / "graphics" / "local_diffusion.py").is_file():
            return repo
        return None

    def available(self) -> bool:
        return self._real_repo() is not None and _RUNNER.is_file()

    def generate(self, prompt: str, negative: str, out_path, seed: int = 0,
                 width: int = 1280, height: int = 720) -> str:
        repo = self._real_repo()
        if not repo:
            raise ProviderUnavailable(
                "Point OPENMONTAGE_REPO at a real OpenMontage clone (with tools/) "
                "to generate scene art with OpenMontage.")
        py = SETTINGS.openmontage_python or "python3"
        cmd = [py, str(_RUNNER),
               "--repo", str(repo),
               "--prompt", (prompt or "")[:1500],
               "--negative", (negative or "")[:500],
               "--out", str(out_path),
               "--seed", str(int(seed) % 2**31),
               "--width", str(width), "--height", str(height),
               "--steps", str(SETTINGS.video_diffusers_steps)]
        try:
            p = subprocess.run(cmd, capture_output=True, text=True,
                               errors="replace", timeout=900)
        except subprocess.TimeoutExpired:
            raise RuntimeError("OpenMontage image generation timed out (15 min)")
        try:
            payload = json.loads((p.stdout or "").strip().splitlines()[-1])
        except Exception:
            payload = {"ok": False, "error": ((p.stderr or p.stdout or "")[-200:])}
        if p.returncode == 0 and payload.get("ok") and Path(out_path).is_file():
            return str(out_path)
        raise RuntimeError(f"OpenMontage image failed: {payload.get('error') or 'unknown'}")
